services:
  # Backend PHP Service
  - type: web
    name: financial-backend
    env: php
    buildCommand: composer install
    startCommand: vendor/bin/heroku-php-apache2 backend/
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://financial-frontend.onrender.com

  # Frontend Static Site
  - type: static
    name: financial-frontend
    staticPublishPath: .
    envVars:
      - key: REACT_APP_API_URL
        value: https://financial-backend.onrender.com 
