<<<<<<< Updated upstream
services:
  - type: web
    name: financial-backend
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t financial-backend .
    startCommand: apache2-foreground
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html
      - key: PHP_INI_SCAN_DIR
        value: /usr/local/etc/php/conf.d:/var/www/html/php.d
    healthCheckPath: /test.php
    autoDeploy: true 
=======
services:
  - type: web
    name: financial-backend
    env: docker
    repo: https://github.com/hdnanda/LEBRONJAMES
    branch: master
    #rootDir: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DB_HOST
        sync: false # Will be set manually in Render dashboard
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ALLOWED_ORIGIN
        value: https://hdnanda.github.io/LEBRONJAMES # GitHub Pages URL 
>>>>>>> Stashed changes
